# .github/workflows/build-and-deploy.yml

name: Build and Deploy CI

on:
  push:
    branches: [ main ]

permissions: read-all|write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: npm
      - name: Build
        run: |
          npm ci
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: out